FROM golang:alpine AS builder
WORKDIR /app
COPY . .
RUN apk add build-base && go mod download
RUN go build -o backend ./cmd/main.go
FROM alpine:3.6
WORKDIR /app
COPY --from=builder /app .
EXPOSE 8080
CMD ["./backend"]