DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS spending;

DROP TABLE IF EXISTS spendingtype;

DROP TABLE IF EXISTS incometype;

DROP TABLE IF EXISTS income;

DROP TABLE IF EXISTS loandebttype;

DROP TABLE IF EXISTS loan;

DROP TABLE IF EXISTS debt;

DROP TABLE IF EXISTS images;

DROP TABLE IF EXISTS planner;